name: Deploy Marketing
on:
  push:
    branches:
      - main
    paths:
      - 'marketing/**'

defaults:
  run:
    working-directory: marketing

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install
      - name: Build Project
        run: yarn build
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1
      - name: Sync with S3
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }}/marketing/latest
      - name: Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/marketing/latest/remoteEntry.js"

